### ISSUE TITLE
Atualizar Readme - Contribuidores

### ISSUE THREAD

**Issue by ErickRock** [free-educa/free-livros#31]
Como faço pra atualizar o Readme do projeto para que eu apareça na lista de contribuidores?

**Comment by islanrodrigues** [comment]
@ErickRock é preciso que seja adicionado uma célula na tabela da seção de contribuidores, dentro do próprio arquivo README.
No repositório não achei nada que informasse se esse processo pode ser feito por nós colaboradores ou se é algo que deve ser restrito aos administradores. 
Abri o PR #33  com adição de novos _ebooks_ e também adicionei um item na seção de contribuidores.

**Comment by danrigoni** [comment]
Exatamente, você pode editar o readme e adicionar este bloco de código html, substituindo as letras maiúsculas pelas suas informações, seguindo o padrão, como você pode ver ao abrir o readme, assim que eu tiver algum tempo colocarei no readme como adicionar, mas por enquanto isso pode ajudá-lo.

<td align="center">
      <a href="https://github.com/SEUGITUB">
        <img
          src="LINKDASUAFOTODOGITHUB"
          width="100px;"
          alt="SEUNOME"
          />
        <br />
        <sub>
          <b>SEUNOME</b>
        </sub>
      </a>
      <br />
      <a href="#content-SEU-NOME" title="Content">🚀</a>
    </td>

**Comment by danrigoni** [comment]
Os links foram corrigidos e um arquivo chamado CONTRIBUTING.md foi adicionado que explicará tudo que precisa para contribuir e adicionar o perfil à lista de contribuidores, obrigado.
