### ISSUE TITLE
Links quebrados no README.md da pasta raiz

### ISSUE THREAD

**Issue by almirleandro** [free-educa/free-livros#32]
Os links "CONTRIBUINDO" e "bem-vindo" no arquivo [README.md](https://github.com/free-educa/free-livros/blob/master/README.md) levam, respectivamente, aos arquivos CONTIBUTING.md e HOWTO.md, que não existem na repo, levando a uma página 404 do GitHub. @danrigoni

**Comment by danrigoni** [comment]
Os links foram corrigidos, e um arquivo chamado CONTRIBUTING.md foi adicionado.
