### ISSUE TITLE
Criar categoria de livros em inglês

### ISSUE THREAD

**Issue by LucasCarrias** [free-educa/free-livros#34]
Como existem muitos livros bacanas exclusivamente em inglês, seria bacana criar um índice no README para livros em inglês e um "Armazém" para esses livros.

**Comment by danrigoni** [comment]
Ótima ideia, criei o repositório para armazenar os livros apenas em inglês [english-books](https://github.com/free-educa/english-books) no momento estou mais focado em criar índices de categorias, mas você pode ficar à vontade para fazer essa contribuição se estiver disposto, obrigado.

**Comment by LucasCarrias** [comment]
Obrigado!

Vou fazer a minha contribuíção por lá.
