### ISSUE TITLE
Proposta de contribuição: desenvolvimento de um site para o projeto

### ISSUE THREAD

**Issue by sebastianrodsouza** [free-educa/free-livros#52]
Olá,

Sou um usuário dos livros e entusiasta do projeto  **free-educa** e gostaria de contribuir com o projeto desenvolvendo um site que possa ajudar na organização da biblioteca. Tenho um protótipo em desenvolvimento que pode ser utilizado como base para o desenvolvimento do site.

O objetivo do site seria criar uma plataforma como essas de bibliotecas online para tornar mais fácil encontrar os livros do projeto. Além disso, no próprio site os administradores iam ter uma área administrativa para lidar com novos upload de livros.

Gostaria de saber se a minha proposta é bem-vinda e se há interesse em colaborar com o desenvolvimento do site. Estou disposto a discutir mais detalhes sobre a proposta e trabalhar em conjunto com a comunidade do projeto para tornar essa ideia uma realidade.

Obrigado.

**Comment by volgarine** [comment]
**Seria ótimo!!!**
